### ISSUE TITLE
Bug on complimentaryColor() ?

### ISSUE THREAD

**Issue by DandyLyons** [Boris-Em/ColorKit#14]
I think this might be a bug? Here's my code.

`let greenComp:UIColor = UIColor.green.complementaryColor //works
let greenCompComp:UIColor = greenComp.complimentaryColor //error: value of type 'UIColor' has no member 'complimentaryColor'`

I know that UIColor does have member complimentaryColor cause it just used it in line 1. Not sure if I did something wrong.

**Comment by Boris-Em** [comment]
Thanks for reaching out @DandyLyons.
You have a type in your second line.
`.complimentaryColor` should be `.complementaryColor`.

**Comment by DandyLyons** [comment]
So sweet. Thank you for the quick response. Haha, sorry I missed such an obvious mistake.
