### ISSUE TITLE
kMeansClustering algorithm: Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by wiencheck** [Boris-Em/ColorKit#20]
Hey, first of all thanks for this amazing, impressive library.

I'd like to report that when using `.kMeansClustering` algorithm, I often get a crash from unwrapping nil value. 
It happens at line 112 in file `ColorPalette.swift`

The image I'm feeding to the algorithm is a transparent PNG (an asset file) so that's probably the cause of it. I know it doesn't make sense to pull colors from such image but the code should fail gracefully in such cases.

**Comment by Boris-Em** [comment]
Closing as fixed with https://github.com/Boris-Em/ColorKit/pull/22.
